<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Matches Java's regular expression syntax.</string>
	<key>fileTypes</key>
	<array>
		<string>re.java</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~J</string>
	<key>name</key>
	<string>Regular Expressions (Java)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\[bBAZzG]|\^|\$</string>
			<key>name</key>
			<string>keyword.control.anchor.regexp.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\(0[0-7]{1,2}|0[0-3][0-7]{2}|x(\h\h|\{\h{,8}\})|u\h{4})</string>
			<key>name</key>
			<string>constant.character.numeric.regexp.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[1-9]\d*</string>
			<key>name</key>
			<string>keyword.other.back-reference.regexp.java</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.back-reference.named.regexp.java</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.back-reference</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.back-reference.named.regexp.java</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\k\&lt;)([a-z]\w*)(\&gt;)</string>
			<key>name</key>
			<string>keyword.other.back-reference.named.regexp.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[?+*][?+]?|\{(\d+,\d+|\d+,|,\d+|\d+)\}[?+]?</string>
			<key>name</key>
			<string>keyword.operator.quantifier.regexp.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>keyword.operator.or.regexp.java</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>We are restrictive in what we allow to go after the comment character to avoid false positives, since the availability of comments depend on regexp flags.</string>
			<key>match</key>
			<string>(?&lt;=^|\s)#\s[[a-zA-Z0-9,. \t?!-:][^\x{00}-\x{7F}]]*$</string>
			<key>name</key>
			<string>comment.line.number-sign.regexp.java</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\?[idmsuxU-]+\)</string>
			<key>name</key>
			<string>keyword.other.option-toggle.regexp.java</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()((\?=)|(\?!)|(\?&lt;=)|(\?&lt;!))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.regexp.java</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.assertion.look-ahead.regexp.java</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>meta.assertion.negative-look-ahead.regexp.java</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.assertion.look-behind.regexp.java</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.assertion.negative-look-behind.regexp.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.regexp.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.assertion.regexp.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()((\?(&gt;|[idmsux-]*:))|(\?&lt;)([a-z]\w*)(&gt;))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.regexp.java</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group-options.regexp.java</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group-options.regexp.java</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.group.regexp.java</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.other.group-options.regexp.java</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.group.regexp.java</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.regexp.java</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#character-class</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>character-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[pP]\{(Lower|Upper|ASCII|Alpha|X?Digit|Alnum|Punct|Graph|Print|Blank|Cntrl|Space)\}</string>
					<key>name</key>
					<string>constant.other.character-class.posix.regexp.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[pP]\{(javaLowerCase|javaUpperCase|javaWhiteSpace|javaMirrored)\}</string>
					<key>name</key>
					<string>constant.other.character-class.java.regexp.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[pP]\{(L[ultmo]?|M[nce]?|N[dlo]?|S[mcko]?|P[cdseifo]?|Z[slp]?|C[cfson]?|IsLatin|InGreek|IsAlphabetic)\}</string>
					<key>name</key>
					<string>constant.other.character-class.unicode.regexp.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[wWsSdDhH]</string>
					<key>name</key>
					<string>constant.character.character-class.regexp.java</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\"(?=[^"]|"{1}|"{3,})|\\[^"]</string>
					<key>name</key>
					<string>constant.character.escape.backslash.regexp.java</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)(\^)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.regexp.java</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.negation.regexp.java</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.character-class.regexp.java</string>
						</dict>
					</dict>
					<key>name</key>
					<string>constant.other.character-class.set.regexp.java</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#character-class</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.backslash.regexp.java</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.backslash.regexp.java</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(.|(\\.))\-([^\]]|(\\.))</string>
							<key>name</key>
							<string>constant.other.character-class.range.regexp.java</string>
						</dict>
						<dict>
							<key>match</key>
							<string>&amp;&amp;</string>
							<key>name</key>
							<string>keyword.operator.intersection.regexp.java</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.regexp.java</string>
	<key>uuid</key>
	<string>4DFB56CF-03CF-4E30-BD84-4CAB83CAAD57</string>
</dict>
</plist>
